#include "objects/m_Object.h"
#include "objects/m_Task.h"
#include "objects/m_Thread.h"
#include "objects/m_DataModel.h"
#include "objects/m_Window.h"
#include "objects/m_Renderer.h"
#include "objects/m_Part.h"
#include "objects/m_Script.h"
#include "objects/m_Camera.h"
#include "objects/m_ShaderScript.h"
#include "objects/m_ShaderProgram.h"
#include "libraries/m_Function.h"
#include "libraries/m_String.h"
#include "libraries/m_Content.h"
#include "services/m_Service.h"
#include "services/m_Stats.h"
#include "services/m_Directory.h"
#include "services/m_RunService.h"
#include "services/m_TaskScheduler.h"
#include "services/m_ShaderService.h"
#include "services/m_Workspace.h"

inline Mariner::Objects::m_DataModel* m_Game = Mariner::Objects::m_DataModel::New();